# As a base I will use nginx:alpine image
FROM nginx:alpine
# Lets remove default nginx conf
RUN rm /etc/nginx/conf.d/default.conf
# Copy our nginx conf to default nginx conf dir
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Lets remove default index.html page and replace it with new
RUN rm /usr/share/nginx/html/index.html
COPY index.html /usr/share/nginx/html/index.html
